// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHc6bflXegWqUTT2qOh1l4jw1UYoVCTtM',
    appId: '1:1005855072612:web:cd13f62aaad293d6bbda71',
    messagingSenderId: '1005855072612',
    projectId: 'vit-auto',
    authDomain: 'vit-auto.firebaseapp.com',
    storageBucket: 'vit-auto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQiWZ18M6mBQS4BFmUMLsdK0iwOK7iPW0',
    appId: '1:1005855072612:android:5c35247ac2f9d89abbda71',
    messagingSenderId: '1005855072612',
    projectId: 'vit-auto',
    storageBucket: 'vit-auto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUlRmWyEAdRV9rmBGO3xnOwMmRAZLLn3s',
    appId: '1:1005855072612:ios:b028e7b5bd2e8a30bbda71',
    messagingSenderId: '1005855072612',
    projectId: 'vit-auto',
    storageBucket: 'vit-auto.firebasestorage.app',
    iosBundleId: 'com.example.vitAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUlRmWyEAdRV9rmBGO3xnOwMmRAZLLn3s',
    appId: '1:1005855072612:ios:b028e7b5bd2e8a30bbda71',
    messagingSenderId: '1005855072612',
    projectId: 'vit-auto',
    storageBucket: 'vit-auto.firebasestorage.app',
    iosBundleId: 'com.example.vitAuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHc6bflXegWqUTT2qOh1l4jw1UYoVCTtM',
    appId: '1:1005855072612:web:3749d47b9ac4b6aabbda71',
    messagingSenderId: '1005855072612',
    projectId: 'vit-auto',
    authDomain: 'vit-auto.firebaseapp.com',
    storageBucket: 'vit-auto.firebasestorage.app',
  );
}
